// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_API.Models;

public partial class Parentplatformofproduct
{
    public int ProductId { get; set; }

    public int ParentPlatformId { get; set; }
}