// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_API.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Slug { get; set; }

    public string Name { get; set; }

    public string BackgroundImage { get; set; }

    public int? MetaCritic { get; set; }

    public int? RatingTop { get; set; }

    public string Description { get; set; }

    public int GenreId { get; set; }

    public int? StoreId { get; set; }

    public int? TrailerId { get; set; }

    public DateTime? CreatedDatetime { get; set; }

    public DateTime? ReleasedDatetime { get; set; }

    public virtual ICollection<Screenshot> Screenshots { get; set; } = new List<Screenshot>();

    public virtual ICollection<Platform> ParentPlatforms { get; set; } = new List<Platform>();

    public virtual ICollection<Platform> Platforms { get; set; } = new List<Platform>();
}