// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_API.Models;

public partial class Screenshot
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedDatetime { get; set; }

    public virtual Product Product { get; set; }
}