// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_API.Models;

public partial class Trailer
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Preview { get; set; }

    public string _480 { get; set; }

    public string Max { get; set; }
}